name: invisible_stitch
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - cuda=12.1
  - h5py=3.11.0
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - numpy=1.26.4
  - pip=22.3.1
  - python=3.10
  - pytorch=2.2.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - scipy=1.13.0
  - torchvision=0.17.0
  - pip:
    - -r requirements.txt
